services:
    sugarcrm_rest:
        class: BisonLab\NoOrmBundle\Services\SugarCrmRestReadonly
        public: true
        arguments:
            - "%sugarcrm_base_url%"
            - "%sugarcrm_username%"
            - "%sugarcrm_password%"

    sugarcrm_account_manager:
        class: BisonLab\SugarCrmBundle\Manager\Account
        public: true
        arguments: [ "@sugarcrm_rest" ]

    sugarcrm_product_manager:
        class: BisonLab\SugarCrmBundle\Manager\Product
        public: true
        arguments: [ "@sugarcrm_rest" ]

    sugarcrm_product_template_manager:
        class: BisonLab\SugarCrmBundle\Manager\ProductTemplate
        public: true
        arguments: [ "@sugarcrm_rest" ]
