services:
    sugar_wrapper:
        class: BisonLab\SugarCrmBundle\Service\SugarWrapper
        arguments:
            - "%sugarcrm_base_url%"
            - "%sugarcrm_username%"
            - "%sugarcrm_password%"

